### ISSUE TITLE
调用报错 Error: Dynamic Linking Error: Win32 error 126

### ISSUE THREAD

**Issue by LiHang941** [sero-cash/js-sero-client#1]
我在调用的时候报错了,我发现在调用静态资源库报错了,是差了什么库吗

```
const sero = require('js-sero-client')
const account = sero.Account
const core = require('js-sero-client/core')
const seedStr = 'fd1b401d2bbfa09fba577b398b09b5ea075bd8f37773095c6e62271a4b080977'

const seed = Buffer.alloc(32, seedStr, 'hex')
const keys = account.NewKeys(seed)
const rnd = core.GetCZero().RandomU32()
var pkr = keys.GenPKr(rnd)

console.log('SK: ' + keys.sk.toString('hex'))

console.log('TK: ' + keys.tk.toString('hex'))

console.log('PK: ' + keys.pk.toString('hex'))

console.log('PKr: ' + pkr.toString('hex'))

if (!keys.IsValidPKr(pkr)) {
  core.ReportError('invalid pkr')
}

if (!keys.IsMyPKr(pkr)) {
  core.ReportError('Is not my pkr')
}


```

**Comment by LiHang941** [comment]
环境 win10 
跟踪ffi发现调用的的路径是正确的，是环境问题吗??

下面是windows下面的报错

```

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (F:\mjoy\coin-service-plugin\node_modules\ffi\lib\dynamic_library.js:74:11)
    at Object.Library (F:\mjoy\coin-service-plugin\node_modules\ffi\lib\library.js:45:12)
    at InitCZero (F:\mjoy\coin-service-plugin\node_modules\js-sero-client\core.js:33:17)
    at Object.<anonymous> (F:\mjoy\coin-service-plugin\node_modules\js-sero-client\core.js:60:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
```


环境 ubuntu 18.04 
报错就更奇怪了,我试图安装 `sudo apt-get install libboost-all-dev` 也没有得到解决
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'libgmpxx.so.4'
    at Object.fs.openSync (fs.js:646:18)
    at fs.readFileSync (fs.js:551:33)
    at new DynamicLibrary (/opt/sero/node_modules/ffi/lib/dynamic_library.js:67:21)
    at Object.Library (/opt/sero/node_modules/ffi/lib/library.js:45:12)
    at InitCZero (/opt/sero/node_modules/js-sero-client/core.js:33:17)
    at Object.<anonymous> (/opt/sero/node_modules/js-sero-client/core.js:60:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by LiHang941** [comment]
差了gmp的库
执行 `sudo apt-get install libgmp-dev` 
就可以成功运行了
